name: Generate Stats Images

on:
  schedule:
    - cron: "0 2 * * SUN"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        architecture: "x64"
        cache: "pip"

    - name: Install requirements
      run: |
        python3 -m pip install -U pip setuptools wheel
        python3 -m pip install -U -r requirements.txt

    - name: Generate images
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        EXCLUDE_FORKED_REPOS: false
      run: |
        python3 generate_images.py

    - name: Commit to the repo
      run: |
        d=`date '+%Y/%m/%dT%H:%M:%SZ'`
        git config --global user.name "EDM115"
        git config --global user.email "github@edm115.dev"
        git add .
        git commit -m "Updated the stats at ${d} [skip ci]" || true
        git push
